version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '9081:80'
      - '9025:25'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080
